version: '3.5'  
volumes:
  myvol:
    name: myvol
services:
  web:
    build:
        dockerfile: Dockerfile
        context: .
    ports:
    - "8080:80"
    volumes:
    - 'myvol:/usr/share/nginx/html'